---
- name: Configure NetBox tenants and sites
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    netbox_api: "{{ lookup('env','NETBOX_API') }}"
    netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"

  collections:
    - netbox.netbox

  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url:   "{{ netbox_api }}"
      netbox_token: "{{ netbox_token }}"
      validate_certs: false
    uri:
      validate_certs: false

  tasks:

    - netbox.netbox.netbox_tenant:
        data:
          name: Vaulter

    - netbox.netbox.netbox_rack_role:
        data:
          name: networking

    - netbox.netbox.netbox_rack_role:
        data:
          name: compute

    - netbox.netbox.netbox_site:
        data:
          name: "165 Halsey"
          description: "https://www.165halsey.com"
          time_zone: "America/New_York"
          physical_address: "165 Halsey Street, Newark, NJ 07102"
          latitude: "40.736906"
          longitude: "-74.173213"

    - netbox.netbox.netbox_location:
        data:
          name: MMR2
          site: "165 Halsey"

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: networking
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: networking
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: compute
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: compute
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_site:
        data:
          name: "375 Pearl"

    - netbox.netbox.netbox_location:
        data:
          name: "30th Floor"
          site: "375 Pearl"

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: networking
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: networking
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: compute
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: compute
          outer_width: 24
          outer_depth: 40
          outer_unit: "Inches"

    - netbox.netbox.netbox_config_context:
        data:
          name: ewr-ntp
          data:
            ntp_servers:
              - "0.pool.ntp.org"
              - "1.pool.ntp.org"
          weight: 1000
          sites:
            - "165 Halsey"

    - netbox.netbox.netbox_config_context:
        data:
          name: jfk-ntp
          data:
            ntp_servers:
              - "2.pool.ntp.org"
              - "3.pool.ntp.org"
          weight: 1000
          sites:
            - "375 Pearl"

    - netbox.netbox.netbox_config_template:
        data:
          name: "ios-ntp-config"
          template_code: |
            {% raw %}
            {% for ntp in ntp_servers %}
            ntp server {{ ntp }}
            {% endfor %}
            {% endraw %}

    - netbox.netbox.netbox_manufacturer:
        data:
          name: Cisco

    - netbox.netbox.netbox_device_type:
        data:
          model: C8000V
          manufacturer: Cisco
          slug: c8000v
          u_height: 1
          is_full_depth: false

    - netbox.netbox.netbox_manufacturer:
        data:
          name: APC
      register: apc_manufacturer

    - name: Check if Rack Type AR3350B2 exists
      uri:
        url: "{{ netbox_api }}api/dcim/rack-types/?slug=ar3350b2"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
      register: rack_type_check

    - name: Create Rack Type AR3350B2
      uri:
        url: "{{ netbox_api }}api/dcim/rack-types/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          manufacturer: "{{ apc_manufacturer.manufacturer.id }}"
          model: "AR3350B2"
          slug: "ar3350b2"
          description: "APC NetShelter SX Server Rack Gen 2"
          comments: "https://www.apc.com/us/en/product/AR3350B2/apc-netshelter-sx-server-rack-gen-2-42u-1991h-x-750w-x-1200d-mm-with-sides-black-taa/"
          form_factor: "4-post-cabinet"
          outer_unit: "mm"
          outer_width: "750"
          outer_depth: "1200"
        status_code: 201
      when: rack_type_check.json.count == 0