---
- name: Configure NetBox tenants and sites
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url:   "{{ lookup('env','NETBOX_API') }}"
      netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"
      validate_certs: false

  collections:
    - netbox.netbox

  tasks:

    - netbox.netbox.netbox_tenant:
        data:
          name: Vaulter

    - netbox.netbox.netbox_rack_role:
        data:
          name: networking

    - netbox.netbox.netbox_rack_role:
        data:
          name: compute

    - netbox.netbox.netbox_site:
        data:
          name: 165Halsey

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: 165Halsey
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: 165Halsey
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: 165Halsey
          rack_role: compute

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: 165Halsey
          rack_role: compute

    - netbox.netbox.netbox_site:
        data:
          name: 375Pearl

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: 375Pearl
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: 375Pearl
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: 375Pearl
          rack_role: compute

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: 375Pearl
          rack_role: compute