---
- name: Configure NetBox tenants and sites
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url:   "{{ lookup('env','NETBOX_API') }}"
      netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"
      validate_certs: false

  collections:
    - netbox.netbox

  tasks:

    - netbox.netbox.netbox_tenant:
        data:
          name: Vaulter

    - netbox.netbox.netbox_rack_role:
        data:
          name: networking

    - netbox.netbox.netbox_rack_role:
        data:
          name: compute

    - netbox.netbox.netbox_site:
        data:
          name: "165 Halsey"

    - netbox.netbox.netbox_location:
        data:
          name: MMR2
          site: "165 Halsey"

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: compute

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: "165 Halsey"
          location: MMR2
          tenant: Vaulter
          rack_role: compute

    - netbox.netbox.netbox_site:
        data:
          name: "375 Pearl"

    - netbox.netbox.netbox_location:
        data:
          name: "30th Floor"
          site: "375 Pearl"

    - netbox.netbox.netbox_rack:
        data:
          name: rack1
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack2
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: networking

    - netbox.netbox.netbox_rack:
        data:
          name: rack3
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: compute

    - netbox.netbox.netbox_rack:
        data:
          name: rack4
          site: "375 Pearl"
          location: "30th Floor"
          tenant: Vaulter
          rack_role: compute